- name: Deploy Zabbix Monitoring Server on Ubuntu
  hosts: zbxhost
  become: yes
  remote_user: zbxadm # Here insert your user for SSH connection
  vars:
    ansible_ssh_pass: Pass_12345 # Here insert your ssh user password
    ansible_become_password: Pass_12345 # Here insert sudoer user password
    db_name: zabbix # Here insert your database name 
    db_user: zabbix # Here insert your database user
    db_password: dbpass_12345 # Here insert your database user's password
    mysql_root_password: dbroot_12345 # Here insert your MySQL administrator's password

  tasks:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation
      shell: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
        sudo mysql -e "DELETE FROM mysql.user WHERE User='';"
        sudo mysql -e "DROP DATABASE IF EXISTS test;"
        sudo mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Install Zabbix repository
      shell: |
        wget https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
        dpkg -i zabbix-release_latest_7.2+ubuntu24.04_all.deb
        apt update

    - name: Install Zabbix server, frontend, agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Install required Python MySQL module
      apt:
        name: python3-pymysql
        state: present

    - name: Create initial database
      shell: "sudo mysql -u root -p{{ mysql_root_password }} -e \"CREATE DATABASE {{ db_name }} CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;\""

    - name: Create MySQL user for Zabbix
      shell: "sudo mysql -u root -p{{ mysql_root_password }} -e \"CREATE USER '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';\""

    - name: Grant privileges on Zabbix database
      shell: "sudo mysql -u root -p{{ mysql_root_password }} -e \"GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'localhost';\""

    - name: Set log_bin_trust_function_creators option
      shell: "sudo mysql -u root -p{{ mysql_root_password }} -e \"SET GLOBAL log_bin_trust_function_creators = 1;\""

    - name: Import initial schema and data
      shell: "zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | sudo mysql --default-character-set=utf8mb4 -u{{ db_user }} -p{{ db_password }} {{ db_name }}"

    - name: Disable log_bin_trust_function_creators option
      shell: "sudo mysql -u root -p{{ mysql_root_password }} -e \"SET GLOBAL log_bin_trust_function_creators = 0;\""

    - name: Configure the database for Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword={{ db_password }}'

    - name: Start Zabbix server and agent processes
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - zabbix-server
        - zabbix-agent
        - apache2

    - name: Enable Zabbix server, agent, and Apache at boot
      systemd:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - apache2
